rating_stars/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import UpdateRatingView


urlpatterns = [
    url(r'^$', UpdateRatingView.as_view(), name='update_rating'),
]

rating_stars/models.py
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext as _

from decimal import Decimal


@python_2_unicode_compatible
class Rating(models.Model):
    votes = models.PositiveIntegerField(_('Amount of vouts'), default=0)
    total = models.PositiveIntegerField(_('Sum of votes'), default=0)
    average = models.DecimalField(
        _('Average rating'),
        max_digits=2, decimal_places=1, default=Decimal(0.0)
    )

    user = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='ratings',
        verbose_name=_('user'),
        blank=True
    )

    content_type = models.ForeignKey(ContentType, null=True, blank=True)
    object_id = models.PositiveIntegerField(null=True, blank=True)
    content_object = GenericForeignKey('content_type', 'object_id')

    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    updated_at = models.DateTimeField(_('updated at'), auto_now=True)

    class Meta:
        verbose_name = _("Rating")
        verbose_name_plural = _("Ratings")

    def __str__(self):
        return u"Rating of %s" % self.content_object

rating_stars/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.utils.translation import ugettext_lazy as _

from .models import Rating


class UpdateRatingForm(forms.Form):
    rating = forms.IntegerField(widget=forms.HiddenInput())
    content_type = forms.CharField(widget=forms.HiddenInput())
    object_id = forms.CharField(widget=forms.HiddenInput())
    user_id = forms.CharField(widget=forms.HiddenInput(), required=False)

    def clean(self):
        cleaned_data = super(UpdateRatingForm, self).clean()
        user_id = cleaned_data.get('user_id')
        ctype_id = cleaned_data.get('content_type')
        obj_id = cleaned_data.get('object_id')

        try:
            user_id = int(user_id)
        except ValueError:
            user_id = -1

        try:
            ctype_id = int(ctype_id)
        except ValueError:
            ctype_id = -1

        try:
            obj_id = int(obj_id)
        except ValueError:
            obj_id = -1

        if not ContentType.objects.filter(id=ctype_id).exists():
            raise forms.ValidationError(
                message=_("Dont change data")
            )
        else:
            ctype = ContentType.objects.get(id=ctype_id)
            if not ctype.model_class().objects.get(id=obj_id):
                raise forms.ValidationError(
                    message=_("Dont change data")
                )

        if not User.objects.filter(id=user_id).exists():
            raise forms.ValidationError(
                message=_("Only authorized user can vote")
            )

        user = User.objects.get(id=user_id)
        if Rating.objects.filter(
            user=user,
            content_type=ctype,
            object_id=obj_id
        ).exists():
            raise forms.ValidationError(
                message=_("You've already voted")
            )
        return cleaned_data

rating_stars/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.http.response import JsonResponse
from django.template.loader import render_to_string
from django.views.generic.edit import CreateView

from .forms import UpdateRatingForm
from .models import Rating


class UpdateRatingView(CreateView):
    model = Rating
    form_class = UpdateRatingForm
    template_name = 'rating_stars/rating.html'

    def get_form_kwargs(self):
        kwargs = {
            'initial': self.get_initial(),
            'prefix': self.get_prefix(),
        }
        if self.request.method in ('POST', 'PUT'):
            kwargs.update({
                'data': self.request.POST,
                'files': self.request.FILES,
            })
        return kwargs

    def form_invalid(self, form):
        ctype_id = form.cleaned_data['content_type']
        ctype = ContentType.objects.get(id=ctype_id)
        obj_id = form.cleaned_data['object_id']
        user_id = form.cleaned_data['user_id']

        disabled = False
        if self.request.user.is_authenticated():
            if Rating.objects.filter(user=self.request.user, object_id=obj_id).exists():
                disabled = True

        if not Rating.objects.filter(content_type=ctype, object_id=obj_id).exists():
            data = {
                'html': render_to_string(
                    'rating_stars/rating.html',
                    {
                        'form': form,
                        'object': ctype.model_class().objects.get(id=obj_id),
                        'vote_user_id': user_id,
                        'vote_amount': 0,
                        'vote_average': 0,
                        'disabled': disabled
                    },
                    request=self.request
                )
            }
        else:
            self.object = Rating.objects.get(content_type=ctype, object_id=obj_id)

            data = {}
            if self.request.is_ajax():
                data = {
                    'html': render_to_string(
                        'rating_stars/rating.html',
                        {
                            'form': form,
                            'object': ctype.model_class().objects.get(id=obj_id),
                            'vote_user_id': user_id,
                            'vote_amount': self.object.votes,
                            'vote_average': self.object.average,
                            'disabled': disabled
                        },
                        request=self.request
                    )
                }
        return JsonResponse(data)

    def form_valid(self, form):
        ctype_id = form.cleaned_data['content_type']
        ctype = ContentType.objects.get(id=ctype_id)
        obj_id = form.cleaned_data['object_id']
        user_id = form.cleaned_data['user_id']
        user = User.objects.get(id=user_id)

        self.object, created_at = Rating.objects.get_or_create(
            content_type=ctype, object_id=obj_id
        )

        self.object.user.add(user)
        self.object.votes = self.object.votes + 1
        self.object.total = self.object.total + form.cleaned_data['rating']
        self.object.average = self.object.total / float(self.object.votes)
        self.object.save()

        data = {}
        if self.request.is_ajax():
            data = {
                'html': render_to_string(
                    'rating_stars/rating.html',
                    {
                        'form': form,
                        'object': ctype.model_class().objects.get(id=obj_id),
                        'vote_user_id': user_id,
                        'vote_amount': self.object.votes,
                        'vote_average': self.object.average,
                        'disabled': True
                    },
                    request=self.request
                )
            }
        return JsonResponse(data)

rating_stars/templates/rating_stars/rating.html
{% load rating_tags i18n %}

  <div itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
      {% if vote_average %}
          <meta itemprop="ratingValue" content="{{ vote_average }}">
      {% else %}
          <meta itemprop="ratingValue" content="5">
      {% endif %}
      <meta itemprop="bestRating" content="5">
      <meta itemprop="worstRating" content="1">
  </div>

  <meta itemprop="mainEntityOfPage" content="{{ object.get_absolute_url }}">
  <meta itemprop="url" content="{{ object.get_absolute_url }}">

  <form action="{% url 'update_rating' %}" id="js-rating-form" method="post">
    {% csrf_token %}
    <ul class="js-star-rating star-rating {% if disabled %}disabled{% endif %}"
          data-init='{{ vote_average|floatformat:"0" }}'>
    </ul>
    <label for='id_object_id'></label>
      <input class="form-control" value='{{ object.id }}'
              id="id_object_id" name="object_id" type="hidden">

    <label for='id_content_type'></label>
      <input class="form-control" value='{{ object|content_type }}'
              id="id_content_type" name="content_type" type="hidden">

    <label for='id_rating'></label>
      <input class="form-control" value=''
              id="id_rating" name="rating" type="hidden">

    <label for='id_user_id'></label>
      <input class="form-control" value='{% if vote_user_id %}{{ vote_user_id }}{% endif %}'
              id="id_user_id" name="user_id" type="hidden">

    {{ form.non_field_errors }}

    <!-- {% if not vote_amount %}
      <p class='margTop20'>
        {% trans 'Nobody voted yet' %}
      </p>
    {% else %}
      <p class='margTop20'>
        {% blocktrans %}Voted: <span itemprop="reviewCount">{{ vote_amount }}</span> times{% endblocktrans %}
      </p>
      <p>
        {% trans 'Average mark' %}: <span itemprop="ratingValue">{{ vote_average|floatformat:"1" }}</span>
      </p>
    {% endif %} -->
  </form>

rating_stars/templates/rating_stars/rating_wrapper.html
<div id='js-rating-wrapper'>
  {% include 'rating_stars/rating.html' %}
</div>